### ISSUE TITLE
安卓手机可以用MX Player 添加网络串流

### ISSUE THREAD

**Issue by lppting** [closetao/TVLive#2]
![qq 20180615191016](https://user-images.githubusercontent.com/26042612/41465224-d093afa8-70cf-11e8-95e8-b11a0fed9672.jpg)
![qq 20180615191028](https://user-images.githubusercontent.com/26042612/41465227-d132f338-70cf-11e8-8499-c092ecbe2c12.jpg)
视频源挺清晰的，真的好用~

**Comment by closetao** [comment]
感谢推荐，又给大家提供了一个选择，我主要用VLC，开源且全平台支持，此外，昨晚发现有些视频源直接就能在微信里打开。
