### ISSUE TITLE
dead man

### ISSUE THREAD

**Issue by fyenne** [closetao/TVLive#3]
不能用

**Comment by closetao** [comment]
2018年06月18日测试如图，可以用呀
![](https://s1.ax1x.com/2018/06/18/CxB8wd.png)

可以多换几个数据源试试，找个能用的，当然建议使用本地播放器直接加载直播源，这样更稳定。

什么问题具体描述下呗

**Comment by linuxxx** [comment]
用不了- -

**Comment by closetao** [comment]
2018年06月21日测试可用，建议如上，就不再贴了。
![截图](https://image.prntscr.com/image/pfPQRjEYSneJjma0ds-Yhg.png)
